---
name: "Jupyter notebook"
"on":
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
permissions:
  contents: "read"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Ensure notebook outputs are cleaned"
      uses: "ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1"
